Update PerforceCheckInConsumer.java
The consumer has received the line of exit status as " exit 0" & the Changelist has been successfully submitted , but the build failed with below exception: 
[ERROR] Provider message:
[ERROR] Unable to submit
[ERROR] Command output:
[ERROR]  exit 0
edit //depot/test/release_version.properties#62
Change 766424 submitted.

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] proj1 ........................................... FAILURE [  8.350 s]
[INFO] proj2 ................................................ SKIPPED
[INFO] proj3 .......................................... SKIPPED
[INFO] proj4 ............................. SKIPPED
[INFO] proj5 ................................. SKIPPED
[INFO] proj6 ........................... SKIPPED
[INFO] proj7 .................................... SKIPPED
[INFO] proj8 ............................. SKIPPED
[INFO] proj9 ........................................ SKIPPED
[INFO] proj10 ....................................... SKIPPED
[INFO] proj11 .......................................... SKIPPED
[INFO] proj12 .......................... SKIPPED
[INFO] proj13 ............................................. SKIPPED
[INFO] proj14 ............................................. SKIPPED
[INFO] proj15 .............................. SKIPPED
[INFO] proj16 ........................ SKIPPED
[INFO] proj17 ....................... SKIPPED
[INFO] proj18 ................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.374 s
[INFO] Finished at: 2016-11-29T17:38:02+05:30
[INFO] Final Memory: 15M/35M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.test.test.versioning:projectversioning-maven-plugin:1.0-SNAPSHOT:CalculateVersionMojoFullBuild (default-cli) on project cih-main: Unable to execute mojo: Command failed.Unable to submit -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.test.test.versioning:projectversioning-maven-plugin:1.0-SNAPSHOT:CalculateVersionMojoFullBuild (default-cli) on project cih-main: Unable to execute mojo
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Unable to execute mojo
        at org.twdata.maven.mojoexecutor.MojoExecutor.executeMojo(MojoExecutor.java:96)
        at com.test.test.CalculateVersionMojoFullBuild.execute(CalculateVersionMojoFullBuild.java:141)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: org.apache.maven.plugin.MojoExecutionException: Command failed.Unable
 to submit
        at org.apache.maven.scm.plugin.AbstractScmMojo.checkResult(AbstractScmMo
jo.java:438)
        at org.apache.maven.scm.plugin.CheckinMojo.execute(CheckinMojo.java:79)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(Default
BuildPluginManager.java:134)
        at org.twdata.maven.mojoexecutor.MojoExecutor.executeMojo(MojoExecutor.j
ava:94)
        ... 23 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionE
xception
[ERROR] Command output: